import os
import argparse
import shutil
from labelme2yolo import Labelme2YOLO
from fix_data import convert_png_to_jpg, fix_labels

# ===== CONFIGURATION =====
# These are the fixed paths based on your previous workflow
JSON_INPUT_DIR = "./forConversion"
YOLO_OUTPUT_DIR = "./forConversion/YOLODataset_seg"

FINAL_IMAGE_DIR = "./jpg_images"
FINAL_LABEL_DIR = "./new_labels"
# =========================

def main():
    parser = argparse.ArgumentParser(description="LabelMe to YOLO + Label Fixer")
    parser.add_argument("--target_label", type=int, required=True,
                        help="Class ID to replace all labels with")
    args = parser.parse_args()

    # 1. Run LabelMe to YOLO conversion
    print("--- Step 1: Converting LabelMe JSON to YOLO Segmentation ---")
    # Fixed parameters: --json_dir ./forConversion/ --seg --val_size 0.1
    convertor = Labelme2YOLO(JSON_INPUT_DIR, to_seg=True)
    convertor.convert(val_size=0.1)

    # 2. Define internal paths for processing (YOLO structure)
    splits = ["train", "val"]
    
    # 3. Process the resulting dataset
    print("\n--- Step 2: Fixing Labels and Converting Images ---")
    for split in splits:
        print(f"\n>> Processing split: {split.upper()}")

        # Source paths generated by Labelme2YOLO
        img_in = os.path.join(YOLO_OUTPUT_DIR, f"images/{split}")
        lbl_in = os.path.join(YOLO_OUTPUT_DIR, f"labels/{split}")

        # Destination paths
        img_out = os.path.join(FINAL_IMAGE_DIR, split)
        lbl_out = os.path.join(FINAL_LABEL_DIR, split)

        # Run functions from fix_data.py
        if os.path.exists(img_in):
            convert_png_to_jpg(img_in, img_out)
        else:
            print(f"[ERROR] Source image directory not found: {img_in}")

        if os.path.exists(lbl_in):
            fix_labels(lbl_in, lbl_out, args.target_label)
        else:
            print(f"[ERROR] Source label directory not found: {lbl_in}")

    print("\n✅ All processes complete.")

if __name__ == "__main__":
    main()